namespace Animarr.Web.Data.Models;

/// <summary>
/// Per-account record. Created either by the first-run Setup wizard (Master)
/// or by an admin from Server Settings → Users. Authentication is cookie-based
/// (see <c>AuthService</c>); the only persistent secret is <see cref="PasswordHash"/>
/// (BCrypt). Passwords are NEVER stored in plaintext, never logged, never
/// returned by any DTO.
/// </summary>
public class User
{
    public Guid Id { get; set; }

    /// <summary>Display name shown in TopBar profile chip + Users list.</summary>
    public string Name { get; set; } = "";

    /// <summary>Login handle — case-insensitive unique. Used in /api/auth/login.</summary>
    public string Username { get; set; } = "";

    /// <summary>Optional contact email — not used for login, just shown in admin.</summary>
    public string? Email { get; set; }

    /// <summary>Optional avatar image path inside the image cache; NULL → use
    /// initials-disc <see cref="AvatarHue"/>.</summary>
    public string? AvatarPath { get; set; }

    /// <summary>Deterministic hue 0..359 for the initials Avatar fallback. Computed
    /// at user-creation time from the username hash so it stays stable across renames.</summary>
    public int AvatarHue { get; set; }

    /// <summary>FK → <see cref="Role.Id"/>. NEVER NULL — every user has a role.</summary>
    public Guid RoleId { get; set; }
    public Role? Role { get; set; }

    /// <summary>BCrypt hash (work factor 12). Generated by AuthService — DO NOT
    /// bypass; raw passwords must never reach this column.</summary>
    public string PasswordHash { get; set; } = "";

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? LastSeenAt { get; set; }
}
