// <auto-generated />
using System;
using Animarr.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Animarr.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702190106_AddAiringSchedule")]
    partial class AddAiringSchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Animarr.Web.Data.Models.AppConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppConfigs");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.EpisodeFileMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<int?>("Episode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId", "FilePath")
                        .IsUnique();

                    b.ToTable("EpisodeFileMappings");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.EpisodeMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AirDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Episode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int?>("RuntimeMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId", "Season", "Episode")
                        .IsUnique();

                    b.ToTable("EpisodeMetadata");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.EpisodeSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("EndSec")
                        .HasColumnType("REAL");

                    b.Property<int>("Episode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StartSec")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId", "Season", "Episode", "Kind")
                        .IsUnique();

                    b.ToTable("EpisodeSegments");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.FolderWatcher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FlatSection")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FolderType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Hue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IdentifyEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSection")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentSectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SingleFilePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WatchEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasFilter("\"SingleFilePath\" IS NULL");

                    b.HasIndex("SingleFilePath")
                        .IsUnique()
                        .HasFilter("\"SingleFilePath\" IS NOT NULL");

                    b.ToTable("FolderWatchers");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.IdentificationQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ForceRefresh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogDetails")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FolderId", "Status");

                    b.ToTable("IdentificationQueues");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiringStatus")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AniListId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CandidatesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CjkTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentRating")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishTitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FanartPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenresJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenresLocalizedJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Hue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdentificationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ImdbConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ImdbId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAiredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastAiredEpisode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAiringCheckAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastMetadataRefreshedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSegmentScanAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastTrickplayScanAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LlmConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("LlmIdentifiedTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("MalConfidence")
                        .HasColumnType("REAL");

                    b.Property<int?>("MalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextAirAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NextEpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Popularity")
                        .HasColumnType("REAL");

                    b.Property<string>("PosterPath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int?>("RatingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Runtime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeasonLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeasonOffsetsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeasonsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Studio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tagline")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemeTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TmdbConfidence")
                        .HasColumnType("REAL");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TvdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AniListId");

                    b.HasIndex("FolderId")
                        .IsUnique();

                    b.HasIndex("IdentificationStatus");

                    b.HasIndex("MalId");

                    b.HasIndex("TmdbId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.MediaItemCategory", b =>
                {
                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("MediaItemId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("CategoryId", "MediaItemId");

                    b.ToTable("MediaItemCategories");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.MediaItemTag", b =>
                {
                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaTagId")
                        .HasColumnType("TEXT");

                    b.HasKey("MediaItemId", "MediaTagId");

                    b.HasIndex("MediaTagId");

                    b.ToTable("MediaItemTags");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.MediaTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoTag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MediaTags");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.RecDismissal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("UserId", "MediaItemId");

                    b.HasIndex("UserId", "TmdbId");

                    b.ToTable("RecDismissals");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.RenamePattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApplicableTo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GlobalPatternId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.ToTable("RenamePatterns");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FoldersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PermManageUsers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PermSystemSettings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PermUploadContent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PermViewContent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.TorrentConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CacheDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DefaultStopAfterDownload")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableDHT")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableLSD")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableUPnP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlobalDownloadLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlobalUploadLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListenPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConnections")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StopSeedingAfterDone")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StopSeedingRatio")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TorrentConfig");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.TorrentFileSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TorrentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TorrentId");

                    b.ToTable("TorrentFileSelections");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.TorrentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomRootFolderName")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadLimit")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Downloaded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FolderWatcherId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MagnetLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SavePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SkipSubfolderStructure")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FlattenSubfolders");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StopAfterDownload")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("StopSeedingRatio")
                        .HasColumnType("REAL");

                    b.Property<bool>("SuppressRootFolder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TorrentFilePath")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UploadLimit")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Uploaded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FolderWatcherId");

                    b.HasIndex("InfoHash")
                        .IsUnique();

                    b.ToTable("TorrentRecords");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.TrickplayAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cols")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DurationSec")
                        .HasColumnType("REAL");

                    b.Property<int?>("Episode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalSec")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rows")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SourceWriteTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpritePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TileHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TileWidth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId", "FilePath")
                        .IsUnique();

                    b.HasIndex("MediaItemId", "Season", "Episode");

                    b.ToTable("TrickplayAssets");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AvatarHue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PinHash")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.UserFavorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "MediaItemId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.UserPreferences", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccentHue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AudioPassthrough")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioPreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("BackdropBlurPx")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackdropBrightness")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BackdropEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackdropIntervalSec")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultVolume")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpisodeListView")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroPagerStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeSectionsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NormalizeVolume")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecsScope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubtitlePreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SubtitleSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ThemeMusicEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThemeMusicVolume")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TvMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.WatchEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Episode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SecondsWatched")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("UserId", "Date");

                    b.HasIndex("UserId", "MediaItemId", "Season", "Episode", "Date")
                        .IsUnique();

                    b.ToTable("WatchEvents");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.WatchState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Episode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWatched")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProgressMs")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RuntimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalWatchTimeSec")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "MediaItemId", "Season", "Episode")
                        .IsUnique();

                    b.ToTable("WatchStates");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.WatchlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("UserId", "MediaItemId");

                    b.HasIndex("UserId", "TmdbId");

                    b.ToTable("WatchlistItems");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.EpisodeFileMapping", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.EpisodeMetadata", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.EpisodeSegment", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.IdentificationQueue", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.FolderWatcher", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.MediaItem", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.FolderWatcher", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.MediaItemCategory", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animarr.Web.Data.Models.MediaItem", "MediaItem")
                        .WithMany("Categories")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.MediaItemTag", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.MediaItem", "MediaItem")
                        .WithMany("Tags")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animarr.Web.Data.Models.MediaTag", "MediaTag")
                        .WithMany("Items")
                        .HasForeignKey("MediaTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("MediaTag");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.RecDismissal", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Animarr.Web.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.RenamePattern", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.FolderWatcher", "Folder")
                        .WithMany("Patterns")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.TorrentFileSelection", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.TorrentRecord", "Torrent")
                        .WithMany("FileSelections")
                        .HasForeignKey("TorrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torrent");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.TorrentRecord", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.FolderWatcher", "FolderWatcher")
                        .WithMany()
                        .HasForeignKey("FolderWatcherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FolderWatcher");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.TrickplayAsset", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.User", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.UserFavorite", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animarr.Web.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.UserPreferences", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.WatchEvent", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animarr.Web.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.WatchState", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animarr.Web.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.WatchlistItem", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Animarr.Web.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.FolderWatcher", b =>
                {
                    b.Navigation("Patterns");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.MediaItem", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.MediaTag", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.TorrentRecord", b =>
                {
                    b.Navigation("FileSelections");
                });
#pragma warning restore 612, 618
        }
    }
}
