// <auto-generated />
using System;
using Animarr.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Animarr.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522185610_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Animarr.Web.Data.Models.AppConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppConfigs");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.FolderWatcher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FlatSection")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FolderType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Hue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IdentifyEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSection")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentSectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RenameEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SingleFilePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WatchEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasFilter("\"SingleFilePath\" IS NULL");

                    b.HasIndex("SingleFilePath")
                        .IsUnique()
                        .HasFilter("\"SingleFilePath\" IS NOT NULL");

                    b.ToTable("FolderWatchers");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.IdentificationQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ForceRefresh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogDetails")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FolderId", "Status");

                    b.ToTable("IdentificationQueues");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.IgnoreRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mask")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.ToTable("IgnoreRules");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidatesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CjkTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentRating")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishTitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FanartPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenresJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Hue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdentificationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ImdbConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ImdbId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastMetadataRefreshedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LlmConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("LlmIdentifiedTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("MalConfidence")
                        .HasColumnType("REAL");

                    b.Property<int?>("MalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Popularity")
                        .HasColumnType("REAL");

                    b.Property<string>("PosterPath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int?>("RatingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Runtime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeasonLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeasonsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Studio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tagline")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TmdbConfidence")
                        .HasColumnType("REAL");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TvdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FolderId")
                        .IsUnique();

                    b.HasIndex("IdentificationStatus");

                    b.HasIndex("MalId");

                    b.HasIndex("TmdbId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.MediaItemTag", b =>
                {
                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaTagId")
                        .HasColumnType("TEXT");

                    b.HasKey("MediaItemId", "MediaTagId");

                    b.HasIndex("MediaTagId");

                    b.ToTable("MediaItemTags");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.MediaTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoTag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MediaTags");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.RenameHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReverted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.ToTable("RenameHistories");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.RenamePattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApplicableTo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GlobalPatternId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.ToTable("RenamePatterns");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.RenameQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("FilePath", "Status");

                    b.ToTable("RenameQueues");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.TorrentConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoRenameAfterDownload")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CacheDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DefaultStopAfterDownload")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableDHT")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableLSD")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableUPnP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlobalDownloadLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlobalUploadLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListenPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConnections")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StopSeedingAfterDone")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StopSeedingRatio")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TorrentConfig");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.TorrentFileSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TorrentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TorrentId");

                    b.ToTable("TorrentFileSelections");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.TorrentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoRename")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomRootFolderName")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadLimit")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Downloaded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FolderWatcherId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MagnetLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SavePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SkipSubfolderStructure")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FlattenSubfolders");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StopAfterDownload")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("StopSeedingRatio")
                        .HasColumnType("REAL");

                    b.Property<bool>("SuppressRootFolder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TorrentFilePath")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UploadLimit")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Uploaded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FolderWatcherId");

                    b.HasIndex("InfoHash")
                        .IsUnique();

                    b.ToTable("TorrentRecords");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.IdentificationQueue", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.FolderWatcher", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.IgnoreRule", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.FolderWatcher", "Folder")
                        .WithMany("IgnoreRules")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.MediaItem", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.FolderWatcher", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.MediaItemTag", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.MediaItem", "MediaItem")
                        .WithMany("Tags")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animarr.Web.Data.Models.MediaTag", "MediaTag")
                        .WithMany("Items")
                        .HasForeignKey("MediaTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("MediaTag");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.RenameHistory", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.FolderWatcher", "Folder")
                        .WithMany("History")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.RenamePattern", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.FolderWatcher", "Folder")
                        .WithMany("Patterns")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.RenameQueue", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.FolderWatcher", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.TorrentFileSelection", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.TorrentRecord", "Torrent")
                        .WithMany("FileSelections")
                        .HasForeignKey("TorrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torrent");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.TorrentRecord", b =>
                {
                    b.HasOne("Animarr.Web.Data.Models.FolderWatcher", "FolderWatcher")
                        .WithMany()
                        .HasForeignKey("FolderWatcherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FolderWatcher");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.FolderWatcher", b =>
                {
                    b.Navigation("History");

                    b.Navigation("IgnoreRules");

                    b.Navigation("Patterns");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.MediaItem", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.MediaTag", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Animarr.Web.Data.Models.TorrentRecord", b =>
                {
                    b.Navigation("FileSelections");
                });
#pragma warning restore 612, 618
        }
    }
}
